### ISSUE TITLE
nng compatibility

### ISSUE THREAD

**Issue by afshin2003** [void-dragon/nanomsg-browser#4] opened 2018-12-03 12:45 UTC
Hi,
Have you ever tested it with nng version? As stated in the documentation, nng is wire compatible with nanomsg. I am just curious about using Connect method instead of Dial to connect to a nng socket.

Afshin

**Comment by void-dragon** [comment] 2019-11-29 05:51
No i never tested this myself.
But if you do i would be glad to here what you find out.

**Comment by TojikCZ** [comment] 2020-05-19 14:37
It seems to work with nng using publish subscribe just fine

**Comment by void-dragon** [comment] 2020-06-05 17:00
i can confirm that NNG works, BUT there are some little things, like nanomsg supported string messages aswell, NNG only takes ArrayBuffer.

But since i could confirm that it works, i will close this ticket now.

**Closed by void-dragon** 2020-06-05 17:00 UTC
