### ISSUE TITLE
not connecting (firefox)

### ISSUE THREAD

**Issue by Alex-CodeLab** [void-dragon/nanomsg-browser#5] opened 2019-07-27 10:25 UTC
On all browsers it works just fine, except when using Firefox (67.0.4 , Ubuntu18.04 ), it never connects.

in debugmode I see this:
```
nanomsg connect to: ws://0.0.0.0:5555/
```
and somewhat later 

```
Firefox can’t establish a connection to the server at ws://0.0.0.0:5555/.
nanomsg close: ws://0.0.0.0:5555/
```

It seems it never  gets to `ws.onopen`

Other browsers work and correctly show:
```
nanomsg connect to: ws://0.0.0.0:5555/
nanomsg.js:1 nanomsg connected: ws://0.0.0.0:5555/
```

**Comment by void-dragon** [comment] 2019-11-29 05:53
That is strange. A quick work around would be to listen on the general state change.

**Comment by void-dragon** [comment] 2020-05-25 07:59
since i was not able to reproduce this error. i will close this issue.

**Closed by void-dragon** 2020-05-25 07:59 UTC
